### ISSUE TITLE
What BlMouseMoveBenchmark class>>#exampleRun is supposed to do ?

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/BlocBenchs#3]
I'm running examples from `BlMouseMoveBenchmark class>>#exampleRun`. A lot of windows are opened and a mouse cursor is painted at the center of each. But nothing is moving. What this benchmark is supposed to do and to measure ? 

![image](https://user-images.githubusercontent.com/49183340/209022247-465e2ca5-2925-42cd-a3f6-79a43627b0c7.png)

My config :

    BlocBenchs dev-1.0
    Bloc dev-1.0
    Windows 11 Pro
    Pharo-11.0.0+build.389

Thanks :)

**Comment by tinchodias** [comment]
Thanks you for asking... I didn't put any explanation in the code. One important information is that Transcript must be open before running the benchmark, to see the results.
I had to browse the class to remember! I will push some updates on the code...

Context: This was an ad-hoc benchmark that I developed in a Workspace not only to measure speed but also to understand more of how the "event bubbling" works in Bloc. Then at tome point, to do not loose the script, I made it a class. And then added this small arrow cursor mostly "for fun".  

Subject: `BlMouseMoveBenchmark>>#mouseMoverLoopOn:at:` emulates a mouse being moved constantly.
The fake events are positioned where that small arrow points. The benchmark iterates over several geometries and hosts because in some combinations, the "hit testing" (determining if clicked point is inside an element) was ending in a FFI call to cairo_in_fill function and was significantly slower.

But after, I implemented the hit testing on Pharo for these geometries so there is no big difference: 
(Copy-pasted from Transcript)
```
Cairo (400@400) (levels=10):
| #                          | Indirect |   Direct |
|----------------------------|----------|----------|
| BlEllipseGeometry          |   900.05 | 28728.76 |
| BlRoundedRectangleGeometry |   898.08 | 29360.18 |
| BlSquareGeometry           |   894.17 | 25400.44 |
| BlRectangleGeometry        |   900.02 | 26758.15 |
| BlCircleGeometry           |   907.22 | 30155.71 |
| BlTriangleGeometry         |   902.58 | 26069.14 |

Cairo (400@400) (levels=5):
| #                          | Indirect |   Direct |
|----------------------------|----------|----------|
| BlEllipseGeometry          |   451.62 | 71607.84 |
| BlRoundedRectangleGeometry |   451.67 | 80020.39 |
| BlSquareGeometry           |   450.82 | 75871.68 |
| BlRectangleGeometry        |   466.96 | 74082.75 |
| BlCircleGeometry           |   451.50 | 83274.95 |
| BlTriangleGeometry         |   450.36 | 62463.01 |

Cairo (400@400) (levels=1):
| #                          | Indirect |    Direct |
|----------------------------|----------|-----------|
| BlEllipseGeometry          |    90.60 | 252609.96 |
| BlRoundedRectangleGeometry |    90.29 | 259802.28 |
| BlSquareGeometry           |    89.96 | 250084.57 |
| BlRectangleGeometry        |    90.20 | 246696.46 |
| BlCircleGeometry           |    90.41 | 262999.40 |
| BlTriangleGeometry         |    90.35 | 222038.78 |
```

**Comment by tinchodias** [comment]
I pushed a little improvement on this benchmark in 36aae5d
